module

public meta import Iris.ProofMode.Aesop.Search.SearchM
public meta import Iris.ProofMode.Aesop.Rule.Types.Info
public meta import Iris.ProofMode.Aesop.Rule.Types.Match
public meta import Iris.ProofMode.Aesop.Tree.Basic

public meta section

namespace Iris.ProofMode.Aesop

open Lean Meta Std

structure RuleInput where
  goal : MVarId
  depth : Nat
  /- all involved meta variables in goal -/
  mvars : Array MVarId
  state : SavedState
  matchResult : RuleMatch

structure RuleReplayInput where
  goal : MVarId
  rapp : Rapp

/- SubGoal produced by a rule application -/
structure SubGoal where
  goal : MVarId
  addedFVars : Std.HashSet FVarId
  removedFVars : Std.HashSet FVarId
  deriving Inhabited

/- Concrete effects produced by a rule application -/
inductive RuleAction where
  | splitGoals (subGoals : Array IrisGoal)
  | manageContext (templates : Array IrisGoal)
  | closeGoal
  deriving Inhabited

/- Information produced by a rule application -/
structure RuleEffect where
  /- Spatial hypotheses generated by this rule application. -/
  generatedSpatialHyps : Array IrisHyp := #[]
  /- Hypotheses consumed by this rule application. -/
  usedHyps : Array AppliedHyp := #[]
  action : Option RuleAction := none
  deriving Inhabited

/- Rule application nodes' specification -/
structure RappSpec where
  goals : Array SubGoal
  postState : SavedState
  successPossibility : Percent
  effect : RuleEffect
  -- [TODO] Add script here

structure RuleOutput where
  rappSepcs : Array RappSpec
  deriving Inhabited

namespace RuleOutput

instance : EmptyCollection RuleOutput where
  emptyCollection := { rappSepcs := #[] }

def ofRappSpec (rappSpec : RappSpec) : RuleOutput :=
  { rappSepcs := #[rappSpec] }

def ofRappSpecs (rappSpecs : Array RappSpec) : RuleOutput :=
  { rappSepcs := rappSpecs }

def ofEffect (postState : SavedState) (effect : RuleEffect)
    (goals : Array SubGoal := #[])
    (successPossibility : Percent := Percent.hundred) : RuleOutput :=
  ofRappSpec { goals, postState, successPossibility, effect := effect }

end RuleOutput

abbrev RuleRunner (Q : Type) [Queue Q] :=
  RuleInput → SearchM Q RuleOutput

abbrev RuleReplayer :=
  RuleReplayInput → ProofModeM (Array MVarId)

end Iris.ProofMode.Aesop
