import Iris.Lithium.Islaris.Isla

namespace Islaris.Instructions.Uart

set_option maxRecDepth 30000 in
abbrev a80188 : IslaTrace := isla%
(trace
  (assume-reg |__highest_el_aarch32| nil false)
  (assume-reg |__currentInstrLength| nil (_ bv4 128))
  (assume-reg |__isla_vector_gpr| nil false)
  (assume-reg |__v85_implemented| nil false)
  (assume-reg |__v84_implemented| nil false)
  (assume-reg |__v83_implemented| nil false)
  (assume-reg |__v81_implemented| nil true)
  (assume-reg |HCR_EL2| nil #x0000000080000000)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL3| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL2| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL1| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL0| nil #x1)
  (assume-reg |TCR_EL2| nil #x0000000000000000)
  (define-enum |signal| 2 (|LOW| |HIGH|))
  (assume-reg |PSTATE| ((_ field |EL|)) #b10)
  (assume-reg |PSTATE| ((_ field |nRW|)) #b0)
  (assume-reg |SCR_EL3| nil #x00000501)
  (cycle)
  (read-reg |SEE| nil (_ bv-1 128))
  (write-reg |SEE| nil (_ bv1461 128))
  (write-reg |__unconditional| nil true)
  (define-enum |ArchVersion| 6 (|ARMv8p0| |ARMv8p1| |ARMv8p2| |ARMv8p3| |ARMv8p4| |ARMv8p5|))
  (read-reg |__v85_implemented| nil false)
  (read-reg |__isla_vector_gpr| nil false)
  (declare-const v26 (_ BitVec 64)) 
  (read-reg |R1| nil v26)
  (define-const v30 (= (bvor #b0 ((_ extract 0 0) (bvlshr ((_ extract 31 0) v26) #x00000005))) #b0))
  (cases "model/aarch64.sail 12130:4 - 12132:5"
    (trace
      (assert v30)
      (declare-const v31 (_ BitVec 64)) 
      (read-reg |_PC| nil v31)
      (define-const v32 (bvadd v31 #xfffffffffffffff8))
      (define-enum |BranchType| 10 (|BranchType_DIRCALL| |BranchType_INDCALL| |BranchType_ERET| |BranchType_DBGEXIT| |BranchType_RET| |BranchType_DIR| |BranchType_INDIR| |BranchType_EXCEPTION| |BranchType_RESET| |BranchType_UNKNOWN|))
      (read-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
      (read-reg |CFG_ID_AA64PFR0_EL1_EL0| nil #x1)
      (read-reg |CFG_ID_AA64PFR0_EL1_EL1| nil #x1)
      (read-reg |CFG_ID_AA64PFR0_EL1_EL2| nil #x1)
      (read-reg |CFG_ID_AA64PFR0_EL1_EL3| nil #x1)
      (read-reg |__highest_el_aarch32| nil false)
      (define-const v33 v32)
      (branch-address v33)
      (define-const v34 v32)
      (read-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b10)))
      (read-reg |SCR_EL3| nil #x00000501)
      (read-reg |__v81_implemented| nil true)
      (read-reg |__v84_implemented| nil false)
      (read-reg |HCR_EL2| nil #x0000000080000000)
      (read-reg |TCR_EL2| nil #x0000000000000000)
      (read-reg |__v83_implemented| nil false)
      (write-reg |_PC| nil v34)
      (write-reg |__PC_changed| nil true)
      (read-reg |__PC_changed| nil true))
    (trace
      (assert (not v30))
      (read-reg |__PC_changed| nil false)
      (declare-const v52 (_ BitVec 64)) 
      (read-reg |_PC| nil v52)
      (read-reg |__currentInstrLength| nil (_ bv4 128))
      (define-const v53 (bvadd v52 #x0000000000000004))
      (write-reg |_PC| nil v53))))
