import Iris.Lithium.Islaris.Isla

namespace Islaris.Instructions

set_option maxRecDepth 30000 in
abbrev instr_str_unaligned : IslaTrace := isla%
(trace
  (assume-reg |__highest_el_aarch32| nil false)
  (assume-reg |__currentInstrLength| nil (_ bv4 128))
  (assume-reg |__isla_vector_gpr| nil false)
  (assume-reg |VBAR_EL2| nil #x0000000000000000)
  (assume-reg |__v85_implemented| nil false)
  (assume-reg |__v84_implemented| nil false)
  (assume-reg |__v83_implemented| nil false)
  (assume-reg |__v82_implemented| nil false)
  (assume-reg |__v81_implemented| nil true)
  (assume-reg |HCR_EL2| nil #x0000000080000000)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL3| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL2| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL1| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL0| nil #x1)
  (assume-reg |TCR_EL2| nil #x0000000000000000)
  (define-enum |signal| 2 (|LOW| |HIGH|))
  (declare-const v0 (_ BitVec 1)) 
  (declare-const v2 (_ BitVec 1)) 
  (declare-const v3 (_ BitVec 1)) 
  (declare-const v7 (_ BitVec 1)) 
  (declare-const v9 (_ BitVec 1)) 
  (declare-const v10 (_ BitVec 1)) 
  (declare-const v14 (_ BitVec 1)) 
  (declare-const v15 (_ BitVec 1)) 
  (declare-const v18 (_ BitVec 1)) 
  (declare-const v23 (_ BitVec 1)) 
  (declare-const v24 (_ BitVec 1)) 
  (assume-reg |PSTATE| ((_ field |EL|)) #b10)
  (assume-reg |PSTATE| ((_ field |SP|)) #b1)
  (assume-reg |PSTATE| ((_ field |nRW|)) #b0)
  (assume-reg |SCR_EL3| nil #x00000501)
  (assume-reg |SCTLR_EL2| nil #x0000000004000002)
  (declare-const v26 (_ BitVec 64)) 
  (assume (= (bvand (|R1| nil) #xfff0000000000007) #x0000000000000001))
  (assert (= (bvand v26 #xfff0000000000007) #x0000000000000001))
  (cycle)
  (read-reg |SEE| nil (_ bv-1 128))
  (write-reg |SEE| nil (_ bv1277 128))
  (write-reg |__unconditional| nil true)
  (define-enum |AccType| 21 (|AccType_NORMAL| |AccType_VEC| |AccType_STREAM| |AccType_VECSTREAM| |AccType_ATOMIC| |AccType_ATOMICRW| |AccType_ORDERED| |AccType_ORDEREDRW| |AccType_ORDEREDATOMIC| |AccType_ORDEREDATOMICRW| |AccType_LIMITEDORDERED| |AccType_UNPRIV| |AccType_IFETCH| |AccType_PTW| |AccType_NV2REGISTER| |AccType_DC| |AccType_DC_UNPRIV| |AccType_IC| |AccType_DCZVA| |AccType_AT| |AccType_TAG|))
  (define-enum |MemOp| 3 (|MemOp_LOAD| |MemOp_STORE| |MemOp_PREFETCH|))
  (define-enum |ArchVersion| 6 (|ARMv8p0| |ARMv8p1| |ARMv8p2| |ARMv8p3| |ARMv8p4| |ARMv8p5|))
  (read-reg |__v85_implemented| nil false)
  (define-enum |Constraint| 15 (|Constraint_NONE| |Constraint_UNKNOWN| |Constraint_UNDEF| |Constraint_UNDEFEL0| |Constraint_NOP| |Constraint_TRUE| |Constraint_FALSE| |Constraint_DISABLED| |Constraint_UNCOND| |Constraint_COND| |Constraint_ADDITIONAL_DECODE| |Constraint_WBSUPPRESS| |Constraint_FAULT| |Constraint_FORCE| |Constraint_FORCENOSLCHECK|))
  (read-reg |__isla_vector_gpr| nil false)
  (read-reg |R1| nil v26)
  (define-const v65 (bvadd v26 #x0000000000000000))
  (declare-const v66 (_ BitVec 64)) 
  (read-reg |R0| nil v66)
  (read-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b10)))
  (read-reg |__v84_implemented| nil false)
  (read-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
  (read-reg |CFG_ID_AA64PFR0_EL1_EL0| nil #x1)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL1| nil #x1)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL2| nil #x1)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL3| nil #x1)
  (read-reg |__highest_el_aarch32| nil false)
  (read-reg |SCTLR_EL2| nil #x0000000004000002)
  (assert (not (= v65 (bvand v65 #xfffffffffffffff8))))
  (declare-const v81 Bool) 
  (define-enum |Fault| 21 (|Fault_None| |Fault_AccessFlag| |Fault_Alignment| |Fault_Background| |Fault_Domain| |Fault_Permission| |Fault_Translation| |Fault_AddressSize| |Fault_SyncExternal| |Fault_SyncExternalOnWalk| |Fault_SyncParity| |Fault_SyncParityOnWalk| |Fault_AsyncParity| |Fault_AsyncExternal| |Fault_Debug| |Fault_TLBConflict| |Fault_BranchTarget| |Fault_HWUpdateAccessFlag| |Fault_Lockdown| |Fault_Exclusive| |Fault_ICacheMaint|))
  (read-reg |SCR_EL3| nil #x00000501)
  (declare-const v176 (_ BitVec 64)) 
  (read-reg |_PC| nil v176)
  (define-const v177 v176)
  (define-enum |Exception| 31 (|Exception_Uncategorized| |Exception_WFxTrap| |Exception_CP15RTTrap| |Exception_CP15RRTTrap| |Exception_CP14RTTrap| |Exception_CP14DTTrap| |Exception_AdvSIMDFPAccessTrap| |Exception_FPIDTrap| |Exception_PACTrap| |Exception_CP14RRTTrap| |Exception_IllegalState| |Exception_SupervisorCall| |Exception_HypervisorCall| |Exception_MonitorCall| |Exception_SystemRegisterTrap| |Exception_ERetTrap| |Exception_InstructionAbort| |Exception_PCAlignment| |Exception_DataAbort| |Exception_NV2DataAbort| |Exception_SPAlignment| |Exception_FPTrappedException| |Exception_SError| |Exception_Breakpoint| |Exception_SoftwareStep| |Exception_Watchpoint| |Exception_SoftwareBreakpoint| |Exception_VectorCatch| |Exception_IRQ| |Exception_BranchTarget| |Exception_FIQ|))
  (read-reg |__v82_implemented| nil false)
  (cases "model/aarch_mem.sail 6858:41 - 6858:77"
    (trace
      (assert v81)
      (define-const v375 v65)
      (assert v81)
      (read-reg |PSTATE| ((_ field |SP|)) (_ struct (|SP| #b1)))
      (read-reg |PSTATE| ((_ field |N|)) (_ struct (|N| v14)))
      (read-reg |PSTATE| ((_ field |Z|)) (_ struct (|Z| v24)))
      (read-reg |PSTATE| ((_ field |C|)) (_ struct (|C| v2)))
      (read-reg |PSTATE| ((_ field |V|)) (_ struct (|V| v23)))
      (read-reg |__v81_implemented| nil true)
      (read-reg |PSTATE| ((_ field |PAN|)) (_ struct (|PAN| v15)))
      (read-reg |PSTATE| ((_ field |SS|)) (_ struct (|SS| v18)))
      (read-reg |PSTATE| ((_ field |IL|)) (_ struct (|IL| v10)))
      (read-reg |PSTATE| ((_ field |D|)) (_ struct (|D| v3)))
      (read-reg |PSTATE| ((_ field |A|)) (_ struct (|A| v0)))
      (read-reg |PSTATE| ((_ field |I|)) (_ struct (|I| v9)))
      (read-reg |PSTATE| ((_ field |F|)) (_ struct (|F| v7)))
      (define-const v400 (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor #x00000000 (bvshl ((_ zero_extend 28) (concat v14 (concat v24 (concat v2 v23)))) #x0000001c)) #xffbfffff) (bvshl ((_ zero_extend 31) v15) #x00000016)) #xffdfffff) (bvshl ((_ zero_extend 31) v18) #x00000015)) #xffefffff) (bvshl ((_ zero_extend 31) v10) #x00000014)) #xfffffc3f) (bvshl ((_ zero_extend 28) (concat v3 (concat v0 (concat v9 v7)))) #x00000006)) #xffffffef) #x00000000) #xfffffff3) #x00000008) #xfffffffe) #x00000001))
      (read-reg |__currentInstrLength| nil (_ bv4 128))
      (write-reg |ESR_EL2| nil #x960000e1)
      (write-reg |FAR_EL2| nil v375)
      (declare-const v405 (_ BitVec 40)) 
      (declare-const v406 (_ BitVec 64)) 
      (read-reg |HPFAR_EL2| nil v406)
      (define-const v407 (bvor (bvand v406 #xfffff0000000000f) (bvshl ((_ zero_extend 24) v405) #x0000000000000004)))
      (write-reg |HPFAR_EL2| nil v407)
      (write-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b10)))
      (write-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
      (write-reg |PSTATE| ((_ field |SP|)) (_ struct (|SP| #b1)))
      (read-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
      (read-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b10)))
      (write-reg |SPSR_EL2| nil v400)
      (write-reg |ELR_EL2| nil v177)
      (write-reg |PSTATE| ((_ field |SS|)) (_ struct (|SS| #b0)))
      (write-reg |PSTATE| ((_ field |D|)) (_ struct (|D| #b1)))
      (write-reg |PSTATE| ((_ field |A|)) (_ struct (|A| #b1)))
      (write-reg |PSTATE| ((_ field |I|)) (_ struct (|I| #b1)))
      (write-reg |PSTATE| ((_ field |F|)) (_ struct (|F| #b1)))
      (write-reg |PSTATE| ((_ field |IL|)) (_ struct (|IL| #b0)))
      (read-reg |HCR_EL2| nil #x0000000080000000)
      (read-reg |VBAR_EL2| nil #x0000000000000000)
      (define-enum |BranchType| 10 (|BranchType_DIRCALL| |BranchType_INDCALL| |BranchType_ERET| |BranchType_DBGEXIT| |BranchType_RET| |BranchType_DIR| |BranchType_INDIR| |BranchType_EXCEPTION| |BranchType_RESET| |BranchType_UNKNOWN|))
      (branch-address #x0000000000000200)
      (read-reg |TCR_EL2| nil #x0000000000000000)
      (read-reg |__v83_implemented| nil false)
      (write-reg |_PC| nil #x0000000000000200)
      (write-reg |__PC_changed| nil true))
    (trace
      (assert (not v81))
      (define-const v436 v65)
      (assert (not v81))
      (read-reg |PSTATE| ((_ field |SP|)) (_ struct (|SP| #b1)))
      (read-reg |PSTATE| ((_ field |N|)) (_ struct (|N| v14)))
      (read-reg |PSTATE| ((_ field |Z|)) (_ struct (|Z| v24)))
      (read-reg |PSTATE| ((_ field |C|)) (_ struct (|C| v2)))
      (read-reg |PSTATE| ((_ field |V|)) (_ struct (|V| v23)))
      (read-reg |__v81_implemented| nil true)
      (read-reg |PSTATE| ((_ field |PAN|)) (_ struct (|PAN| v15)))
      (read-reg |PSTATE| ((_ field |SS|)) (_ struct (|SS| v18)))
      (read-reg |PSTATE| ((_ field |IL|)) (_ struct (|IL| v10)))
      (read-reg |PSTATE| ((_ field |D|)) (_ struct (|D| v3)))
      (read-reg |PSTATE| ((_ field |A|)) (_ struct (|A| v0)))
      (read-reg |PSTATE| ((_ field |I|)) (_ struct (|I| v9)))
      (read-reg |PSTATE| ((_ field |F|)) (_ struct (|F| v7)))
      (define-const v461 (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor #x00000000 (bvshl ((_ zero_extend 28) (concat v14 (concat v24 (concat v2 v23)))) #x0000001c)) #xffbfffff) (bvshl ((_ zero_extend 31) v15) #x00000016)) #xffdfffff) (bvshl ((_ zero_extend 31) v18) #x00000015)) #xffefffff) (bvshl ((_ zero_extend 31) v10) #x00000014)) #xfffffc3f) (bvshl ((_ zero_extend 28) (concat v3 (concat v0 (concat v9 v7)))) #x00000006)) #xffffffef) #x00000000) #xfffffff3) #x00000008) #xfffffffe) #x00000001))
      (read-reg |__currentInstrLength| nil (_ bv4 128))
      (write-reg |ESR_EL2| nil #x96000061)
      (write-reg |FAR_EL2| nil v436)
      (declare-const v466 (_ BitVec 40)) 
      (declare-const v467 (_ BitVec 64)) 
      (read-reg |HPFAR_EL2| nil v467)
      (define-const v468 (bvor (bvand v467 #xfffff0000000000f) (bvshl ((_ zero_extend 24) v466) #x0000000000000004)))
      (write-reg |HPFAR_EL2| nil v468)
      (write-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b10)))
      (write-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
      (write-reg |PSTATE| ((_ field |SP|)) (_ struct (|SP| #b1)))
      (read-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
      (read-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b10)))
      (write-reg |SPSR_EL2| nil v461)
      (write-reg |ELR_EL2| nil v177)
      (write-reg |PSTATE| ((_ field |SS|)) (_ struct (|SS| #b0)))
      (write-reg |PSTATE| ((_ field |D|)) (_ struct (|D| #b1)))
      (write-reg |PSTATE| ((_ field |A|)) (_ struct (|A| #b1)))
      (write-reg |PSTATE| ((_ field |I|)) (_ struct (|I| #b1)))
      (write-reg |PSTATE| ((_ field |F|)) (_ struct (|F| #b1)))
      (write-reg |PSTATE| ((_ field |IL|)) (_ struct (|IL| #b0)))
      (read-reg |HCR_EL2| nil #x0000000080000000)
      (read-reg |VBAR_EL2| nil #x0000000000000000)
      (define-enum |BranchType| 10 (|BranchType_DIRCALL| |BranchType_INDCALL| |BranchType_ERET| |BranchType_DBGEXIT| |BranchType_RET| |BranchType_DIR| |BranchType_INDIR| |BranchType_EXCEPTION| |BranchType_RESET| |BranchType_UNKNOWN|))
      (branch-address #x0000000000000200)
      (read-reg |TCR_EL2| nil #x0000000000000000)
      (read-reg |__v83_implemented| nil false)
      (write-reg |_PC| nil #x0000000000000200)
      (write-reg |__PC_changed| nil true))))
