import Iris.Lithium.Islaris.Isla

namespace Islaris.Instructions.Memcpy

set_option maxRecDepth 30000 in
abbrev ac : IslaTrace := isla%
(trace
  (assume-reg |__monomorphize_writes| nil false)
  (assume-reg |__highest_el_aarch32| nil false)
  (assume-reg |__currentInstrLength| nil (_ bv4 128))
  (assume-reg |__CNTControlBase| nil #x0000000000000)
  (assume-reg |__isla_vector_gpr| nil false)
  (assume-reg |__v85_implemented| nil false)
  (assume-reg |__v84_implemented| nil false)
  (assume-reg |__v83_implemented| nil false)
  (assume-reg |__v82_implemented| nil false)
  (assume-reg |__v81_implemented| nil true)
  (assume-reg |__trickbox_enabled| nil false)
  (assume-reg |HCR_EL2| nil #x0000000080000000)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL3| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL2| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL1| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL0| nil #x1)
  (assume-reg |TCR_EL2| nil #x0000000000000000)
  (define-enum |signal| 2 (|LOW| |HIGH|))
  (assume-reg |EDSCR| nil #x00000000)
  (assume-reg |OSDLR_EL1| nil #x00000000)
  (assume-reg |OSLSR_EL1| nil #x00000000)
  (declare-const v3 (_ BitVec 1)) 
  (assume-reg |PSTATE| ((_ field |EL|)) #b10)
  (assume-reg |PSTATE| ((_ field |nRW|)) #b0)
  (assume-reg |SCR_EL3| nil #x00000501)
  (assume-reg |SCTLR_EL2| nil #x0000000004000002)
  (declare-const v26 (_ BitVec 64)) 
  (declare-const v27 (_ BitVec 64)) 
  (assume (= (bvand (bvadd (|R0| nil) (|R3| nil)) #xfff0000000000000) #x0000000000000000))
  (assert (= (bvand (bvadd v26 v27) #xfff0000000000000) #x0000000000000000))
  (cycle)
  (read-reg |SEE| nil (_ bv-1 128))
  (write-reg |SEE| nil (_ bv1717 128))
  (write-reg |__unconditional| nil true)
  (define-enum |ExtendType| 8 (|ExtendType_SXTB| |ExtendType_SXTH| |ExtendType_SXTW| |ExtendType_SXTX| |ExtendType_UXTB| |ExtendType_UXTH| |ExtendType_UXTW| |ExtendType_UXTX|))
  (define-enum |AccType| 21 (|AccType_NORMAL| |AccType_VEC| |AccType_STREAM| |AccType_VECSTREAM| |AccType_ATOMIC| |AccType_ATOMICRW| |AccType_ORDERED| |AccType_ORDEREDRW| |AccType_ORDEREDATOMIC| |AccType_ORDEREDATOMICRW| |AccType_LIMITEDORDERED| |AccType_UNPRIV| |AccType_IFETCH| |AccType_PTW| |AccType_NV2REGISTER| |AccType_DC| |AccType_DC_UNPRIV| |AccType_IC| |AccType_DCZVA| |AccType_AT| |AccType_TAG|))
  (define-enum |MemOp| 3 (|MemOp_LOAD| |MemOp_STORE| |MemOp_PREFETCH|))
  (define-enum |ArchVersion| 6 (|ARMv8p0| |ARMv8p1| |ARMv8p2| |ARMv8p3| |ARMv8p4| |ARMv8p5|))
  (read-reg |__v85_implemented| nil false)
  (read-reg |__isla_vector_gpr| nil false)
  (read-reg |R3| nil v27)
  (define-enum |Constraint| 15 (|Constraint_NONE| |Constraint_UNKNOWN| |Constraint_UNDEF| |Constraint_UNDEFEL0| |Constraint_NOP| |Constraint_TRUE| |Constraint_FALSE| |Constraint_DISABLED| |Constraint_UNCOND| |Constraint_COND| |Constraint_ADDITIONAL_DECODE| |Constraint_WBSUPPRESS| |Constraint_FAULT| |Constraint_FORCE| |Constraint_FORCENOSLCHECK|))
  (read-reg |R0| nil v26)
  (define-const v70 (bvadd v26 v27))
  (declare-const v71 (_ BitVec 64)) 
  (read-reg |R4| nil v71)
  (define-const v72 ((_ extract 7 0) v71))
  (read-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b10)))
  (read-reg |__v84_implemented| nil false)
  (read-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
  (read-reg |CFG_ID_AA64PFR0_EL1_EL0| nil #x1)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL1| nil #x1)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL2| nil #x1)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL3| nil #x1)
  (read-reg |__highest_el_aarch32| nil false)
  (read-reg |SCTLR_EL2| nil #x0000000004000002)
  (define-const v77 (= v70 (bvand v70 #xffffffffffffffff)))
  (assert (not (not v77)))
  (assert (not (not v77)))
  (assert (= v70 (bvand v70 #xffffffffffffffff)))
  (define-enum |Fault| 21 (|Fault_None| |Fault_AccessFlag| |Fault_Alignment| |Fault_Background| |Fault_Domain| |Fault_Permission| |Fault_Translation| |Fault_AddressSize| |Fault_SyncExternal| |Fault_SyncExternalOnWalk| |Fault_SyncParity| |Fault_SyncParityOnWalk| |Fault_AsyncParity| |Fault_AsyncExternal| |Fault_Debug| |Fault_TLBConflict| |Fault_BranchTarget| |Fault_HWUpdateAccessFlag| |Fault_Lockdown| |Fault_Exclusive| |Fault_ICacheMaint|))
  (define-enum |MemType| 2 (|MemType_Normal| |MemType_Device|))
  (define-enum |DeviceType| 4 (|DeviceType_GRE| |DeviceType_nGRE| |DeviceType_nGnRE| |DeviceType_nGnRnE|))
  (read-reg |SCR_EL3| nil #x00000501)
  (read-reg |__v81_implemented| nil true)
  (read-reg |HCR_EL2| nil #x0000000080000000)
  (read-reg |TCR_EL2| nil #x0000000000000000)
  (read-reg |__v83_implemented| nil false)
  (assert (not (not (= ((_ extract 63 52) v70) #x000))))
  (assert (not (not v77)))
  (read-reg |PSTATE| ((_ field |D|)) (_ struct (|D| v3)))
  (read-reg |OSLSR_EL1| nil #x00000000)
  (read-reg |OSDLR_EL1| nil #x00000000)
  (read-reg |EDSCR| nil #x00000000)
  (define-const v1251 v70)
  (declare-const v1252 (_ BitVec 64)) 
  (read-reg |MPIDR_EL1| nil v1252)
  (read-reg |__v82_implemented| nil false)
  (read-reg |__trickbox_enabled| nil false)
  (read-reg |__CNTControlBase| nil #x0000000000000)
  (define-const v1406 (concat #x0 ((_ extract 51 0) v70)))
  (define-enum |Access_strength| 3 (|AS_normal| |AS_rel_or_acq| |AS_acq_rcpc|))
  (define-enum |Access_variety| 3 (|AV_plain| |AV_exclusive| |AV_atomic_rmw|))
  (define-const v1407 ((_ zero_extend 8) v1406))
  (read-reg |__monomorphize_writes| nil false)
  (declare-const v1408 Bool) 
  (write-mem v1408 (_ struct (|value| (|Some| v72)) (|pa| v1406) (|access_kind| (|AK_explicit| (_ struct (|variety| |AV_plain|) (|strength| |AS_normal|)))) (|tag| (|None| (_ unit))) (|translation| (|None| (_ unit))) (|va| (|Some| v1251)) (|size| (_ bv1 128))) v1407 v72 1)
  (read-reg |__PC_changed| nil false)
  (declare-const v1409 (_ BitVec 64)) 
  (read-reg |_PC| nil v1409)
  (read-reg |__currentInstrLength| nil (_ bv4 128))
  (define-const v1410 (bvadd v1409 #x0000000000000004))
  (write-reg |_PC| nil v1410))
