import Iris.Lithium.Islaris.Isla

namespace Islaris.Instructions.BinarySearch

set_option maxRecDepth 30000 in
abbrev a3c : IslaTrace := isla%
(trace
  (assume-reg |__highest_el_aarch32| nil false)
  (assume-reg |__isla_vector_gpr| nil false)
  (assume-reg |__v85_implemented| nil false)
  (assume-reg |__v84_implemented| nil false)
  (assume-reg |__v83_implemented| nil false)
  (assume-reg |__v81_implemented| nil true)
  (assume-reg |HCR_EL2| nil #x0000000080000000)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL3| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL2| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL1| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL0| nil #x1)
  (assume-reg |TCR_EL2| nil #x0000000000000000)
  (define-enum |signal| 2 (|LOW| |HIGH|))
  (assume-reg |PSTATE| ((_ field |EL|)) #b10)
  (assume-reg |PSTATE| ((_ field |nRW|)) #b0)
  (assume-reg |SCR_EL3| nil #x00000501)
  (cycle)
  (read-reg |SEE| nil (_ bv-1 128))
  (write-reg |SEE| nil (_ bv1345 128))
  (write-reg |__unconditional| nil true)
  (define-enum |BranchType| 10 (|BranchType_DIRCALL| |BranchType_INDCALL| |BranchType_ERET| |BranchType_DBGEXIT| |BranchType_RET| |BranchType_DIR| |BranchType_INDIR| |BranchType_EXCEPTION| |BranchType_RESET| |BranchType_UNKNOWN|))
  (define-enum |ArchVersion| 6 (|ARMv8p0| |ARMv8p1| |ARMv8p2| |ARMv8p3| |ARMv8p4| |ARMv8p5|))
  (read-reg |__v85_implemented| nil false)
  (read-reg |__isla_vector_gpr| nil false)
  (declare-const v44 (_ BitVec 64)) 
  (read-reg |R22| nil v44)
  (define-const v45 v44)
  (write-reg |BTypeNext| nil #b10)
  (mark-reg |R22| "ignore_edge")
  (mark-reg |R30| "ignore_edge")
  (declare-const v46 (_ BitVec 64)) 
  (read-reg |_PC| nil v46)
  (define-const v48 (bvadd v46 #x0000000000000004))
  (write-reg |R30| nil v48)
  (read-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
  (read-reg |CFG_ID_AA64PFR0_EL1_EL0| nil #x1)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL1| nil #x1)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL2| nil #x1)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL3| nil #x1)
  (read-reg |__highest_el_aarch32| nil false)
  (define-const v49 v45)
  (branch-address v49)
  (define-const v50 v45)
  (read-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b10)))
  (read-reg |SCR_EL3| nil #x00000501)
  (read-reg |__v81_implemented| nil true)
  (read-reg |__v84_implemented| nil false)
  (read-reg |HCR_EL2| nil #x0000000080000000)
  (read-reg |TCR_EL2| nil #x0000000000000000)
  (read-reg |__v83_implemented| nil false)
  (write-reg |_PC| nil v50)
  (write-reg |__PC_changed| nil true)
  (read-reg |__PC_changed| nil true))
