import Iris.Lithium.Islaris.Isla

namespace Islaris.Instructions.BinarySearch

set_option maxRecDepth 30000 in
abbrev a40 : IslaTrace := isla%
(trace
  (assume-reg |__currentInstrLength| nil (_ bv4 128))
  (assume-reg |__isla_vector_gpr| nil false)
  (assume-reg |__v85_implemented| nil false)
  (define-enum |signal| 2 (|LOW| |HIGH|))
  (cycle)
  (read-reg |SEE| nil (_ bv-1 128))
  (write-reg |SEE| nil (_ bv1658 128))
  (write-reg |__unconditional| nil true)
  (define-enum |LogicalOp| 3 (|LogicalOp_AND| |LogicalOp_EOR| |LogicalOp_ORR|))
  (define-enum |ArchVersion| 6 (|ARMv8p0| |ARMv8p1| |ARMv8p2| |ARMv8p3| |ARMv8p4| |ARMv8p5|))
  (read-reg |__v85_implemented| nil false)
  (read-reg |__isla_vector_gpr| nil false)
  (declare-const v41 (_ BitVec 64)) 
  (read-reg |R0| nil v41)
  (define-const v43 (bvand ((_ extract 31 0) v41) #x00000001))
  (define-const v45 (bvor #b0 ((_ extract 0 0) (bvlshr v43 #x0000001f))))
  (define-const v46 (= v43 #x00000000))
  (cases "model/aarch64.sail 4040:4 - 4040:34"
    (trace
      (assert v46)
      (define-const v48 (concat (concat v45 #b1) #b00))
      (define-const v49 ((_ extract 3 3) v48))
      (write-reg |PSTATE| ((_ field |N|)) (_ struct (|N| v49)))
      (define-const v50 ((_ extract 2 2) v48))
      (write-reg |PSTATE| ((_ field |Z|)) (_ struct (|Z| v50)))
      (define-const v51 ((_ extract 1 1) v48))
      (write-reg |PSTATE| ((_ field |C|)) (_ struct (|C| v51)))
      (define-const v52 ((_ extract 0 0) v48))
      (write-reg |PSTATE| ((_ field |V|)) (_ struct (|V| v52)))
      (read-reg |__PC_changed| nil false)
      (declare-const v53 (_ BitVec 64)) 
      (read-reg |_PC| nil v53)
      (read-reg |__currentInstrLength| nil (_ bv4 128))
      (define-const v54 (bvadd v53 #x0000000000000004))
      (write-reg |_PC| nil v54))
    (trace
      (assert (not v46))
      (define-const v56 (concat (concat v45 #b0) #b00))
      (define-const v57 ((_ extract 3 3) v56))
      (write-reg |PSTATE| ((_ field |N|)) (_ struct (|N| v57)))
      (define-const v58 ((_ extract 2 2) v56))
      (write-reg |PSTATE| ((_ field |Z|)) (_ struct (|Z| v58)))
      (define-const v59 ((_ extract 1 1) v56))
      (write-reg |PSTATE| ((_ field |C|)) (_ struct (|C| v59)))
      (define-const v60 ((_ extract 0 0) v56))
      (write-reg |PSTATE| ((_ field |V|)) (_ struct (|V| v60)))
      (read-reg |__PC_changed| nil false)
      (declare-const v61 (_ BitVec 64)) 
      (read-reg |_PC| nil v61)
      (read-reg |__currentInstrLength| nil (_ bv4 128))
      (define-const v62 (bvadd v61 #x0000000000000004))
      (write-reg |_PC| nil v62))))
