name = "irisitree"
defaultTargets = ["IrisITree"]

[[require]]
name = "iris"
path = "../Iris"

[[require]]
name = "Coinductive"
scope = "ISTA-PLV"
rev = "d1aeffe87ec7bd4bd13ed92fdc00ef6c5d58f800"

[[lean_lib]]
name = "IrisITree"
