import Iris.Lithium.Islaris.Isla

namespace Islaris.Instructions.SimpleHvc

set_option maxRecDepth 30000 in
abbrev a90004 : IslaTrace := isla%
(trace
  (assume-reg |__highest_el_aarch32| nil false)
  (assume-reg |__currentInstrLength| nil (_ bv4 128))
  (assume-reg |__v85_implemented| nil false)
  (assume-reg |__v84_implemented| nil false)
  (assume-reg |__v83_implemented| nil false)
  (assume-reg |__v82_implemented| nil false)
  (assume-reg |__v81_implemented| nil true)
  (assume-reg |MDSCR_EL1| nil #x00000000)
  (assume-reg |HCR_EL2| nil #x0000000080000000)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL3| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL2| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL1| nil #x1)
  (assume-reg |CFG_ID_AA64PFR0_EL1_EL0| nil #x1)
  (assume-reg |TCR_EL2| nil #x0000000000000000)
  (define-enum |signal| 2 (|LOW| |HIGH|))
  (assume-reg |MDCR_EL2| nil #x00000000)
  (declare-const v0 (_ BitVec 1)) 
  (declare-const v2 (_ BitVec 1)) 
  (declare-const v3 (_ BitVec 1)) 
  (declare-const v7 (_ BitVec 1)) 
  (declare-const v9 (_ BitVec 1)) 
  (declare-const v10 (_ BitVec 1)) 
  (declare-const v14 (_ BitVec 1)) 
  (declare-const v15 (_ BitVec 1)) 
  (declare-const v18 (_ BitVec 1)) 
  (declare-const v23 (_ BitVec 1)) 
  (declare-const v24 (_ BitVec 1)) 
  (assume-reg |PSTATE| ((_ field |EL|)) #b01)
  (assume-reg |PSTATE| ((_ field |SP|)) #b0)
  (assume-reg |PSTATE| ((_ field |nRW|)) #b0)
  (assume-reg |SCR_EL3| nil #x00000501)
  (assume-reg |SCTLR_EL1| nil #x0000000004000002)
  (declare-const v26 (_ BitVec 64)) 
  (assume (= (|VBAR_EL2| nil) #x00000000000a0000))
  (assert (= v26 #x00000000000a0000))
  (cycle)
  (read-reg |SEE| nil (_ bv-1 128))
  (write-reg |SEE| nil (_ bv1557 128))
  (write-reg |__unconditional| nil true)
  (define-enum |ArchVersion| 6 (|ARMv8p0| |ARMv8p1| |ARMv8p2| |ARMv8p3| |ARMv8p4| |ARMv8p5|))
  (read-reg |__v85_implemented| nil false)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL2| nil #x1)
  (read-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b01)))
  (read-reg |__v84_implemented| nil false)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL3| nil #x1)
  (read-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
  (read-reg |CFG_ID_AA64PFR0_EL1_EL0| nil #x1)
  (read-reg |CFG_ID_AA64PFR0_EL1_EL1| nil #x1)
  (read-reg |__highest_el_aarch32| nil false)
  (read-reg |SCR_EL3| nil #x00000501)
  (read-reg |MDCR_EL2| nil #x00000000)
  (read-reg |HCR_EL2| nil #x0000000080000000)
  (read-reg |MDSCR_EL1| nil #x00000000)
  (declare-const v45 (_ BitVec 64)) 
  (read-reg |_PC| nil v45)
  (read-reg |__currentInstrLength| nil (_ bv4 128))
  (define-const v47 (bvadd v45 #x0000000000000004))
  (define-enum |Exception| 31 (|Exception_Uncategorized| |Exception_WFxTrap| |Exception_CP15RTTrap| |Exception_CP15RRTTrap| |Exception_CP14RTTrap| |Exception_CP14DTTrap| |Exception_AdvSIMDFPAccessTrap| |Exception_FPIDTrap| |Exception_PACTrap| |Exception_CP14RRTTrap| |Exception_IllegalState| |Exception_SupervisorCall| |Exception_HypervisorCall| |Exception_MonitorCall| |Exception_SystemRegisterTrap| |Exception_ERetTrap| |Exception_InstructionAbort| |Exception_PCAlignment| |Exception_DataAbort| |Exception_NV2DataAbort| |Exception_SPAlignment| |Exception_FPTrappedException| |Exception_SError| |Exception_Breakpoint| |Exception_SoftwareStep| |Exception_Watchpoint| |Exception_SoftwareBreakpoint| |Exception_VectorCatch| |Exception_IRQ| |Exception_BranchTarget| |Exception_FIQ|))
  (read-reg |__v82_implemented| nil false)
  (read-reg |SCTLR_EL1| nil #x0000000004000002)
  (read-reg |__v81_implemented| nil true)
  (read-reg |PSTATE| ((_ field |N|)) (_ struct (|N| v14)))
  (read-reg |PSTATE| ((_ field |Z|)) (_ struct (|Z| v24)))
  (read-reg |PSTATE| ((_ field |C|)) (_ struct (|C| v2)))
  (read-reg |PSTATE| ((_ field |V|)) (_ struct (|V| v23)))
  (read-reg |PSTATE| ((_ field |PAN|)) (_ struct (|PAN| v15)))
  (read-reg |PSTATE| ((_ field |SS|)) (_ struct (|SS| v18)))
  (read-reg |PSTATE| ((_ field |IL|)) (_ struct (|IL| v10)))
  (read-reg |PSTATE| ((_ field |D|)) (_ struct (|D| v3)))
  (read-reg |PSTATE| ((_ field |A|)) (_ struct (|A| v0)))
  (read-reg |PSTATE| ((_ field |I|)) (_ struct (|I| v9)))
  (read-reg |PSTATE| ((_ field |F|)) (_ struct (|F| v7)))
  (read-reg |PSTATE| ((_ field |SP|)) (_ struct (|SP| #b0)))
  (define-const v218 (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor (bvand (bvor #x00000000 (bvshl ((_ zero_extend 28) (concat v14 (concat v24 (concat v2 v23)))) #x0000001c)) #xffbfffff) (bvshl ((_ zero_extend 31) v15) #x00000016)) #xffdfffff) (bvshl ((_ zero_extend 31) v18) #x00000015)) #xffefffff) (bvshl ((_ zero_extend 31) v10) #x00000014)) #xfffffc3f) (bvshl ((_ zero_extend 28) (concat v3 (concat v0 (concat v9 v7)))) #x00000006)) #xffffffef) #x00000000) #xfffffff3) #x00000004) #xfffffffe) #x00000000))
  (write-reg |ESR_EL2| nil #x5a000000)
  (declare-const v223 (_ BitVec 64)) 
  (write-reg |FAR_EL2| nil v223)
  (declare-const v224 (_ BitVec 40)) 
  (declare-const v225 (_ BitVec 64)) 
  (read-reg |HPFAR_EL2| nil v225)
  (define-const v226 (bvor (bvand v225 #xfffff0000000000f) (bvshl ((_ zero_extend 24) v224) #x0000000000000004)))
  (write-reg |HPFAR_EL2| nil v226)
  (write-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b10)))
  (write-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
  (write-reg |PSTATE| ((_ field |SP|)) (_ struct (|SP| #b1)))
  (read-reg |PSTATE| ((_ field |nRW|)) (_ struct (|nRW| #b0)))
  (read-reg |PSTATE| ((_ field |EL|)) (_ struct (|EL| #b10)))
  (write-reg |SPSR_EL2| nil v218)
  (write-reg |ELR_EL2| nil v47)
  (write-reg |PSTATE| ((_ field |SS|)) (_ struct (|SS| #b0)))
  (write-reg |PSTATE| ((_ field |D|)) (_ struct (|D| #b1)))
  (write-reg |PSTATE| ((_ field |A|)) (_ struct (|A| #b1)))
  (write-reg |PSTATE| ((_ field |I|)) (_ struct (|I| #b1)))
  (write-reg |PSTATE| ((_ field |F|)) (_ struct (|F| #b1)))
  (write-reg |PSTATE| ((_ field |IL|)) (_ struct (|IL| #b0)))
  (read-reg |VBAR_EL2| nil v26)
  (define-const v238 (concat ((_ extract 63 11) v26) #b10000000000))
  (define-enum |BranchType| 10 (|BranchType_DIRCALL| |BranchType_INDCALL| |BranchType_ERET| |BranchType_DBGEXIT| |BranchType_RET| |BranchType_DIR| |BranchType_INDIR| |BranchType_EXCEPTION| |BranchType_RESET| |BranchType_UNKNOWN|))
  (define-const v239 v238)
  (branch-address v239)
  (define-const v240 v238)
  (read-reg |TCR_EL2| nil #x0000000000000000)
  (read-reg |__v83_implemented| nil false)
  (write-reg |_PC| nil v240)
  (write-reg |__PC_changed| nil true))
